### ISSUE TITLE
personnal email in webpage

### ISSUE THREAD

**Issue by Ddataa** [YunoHost-Apps/my_webdav_ynh#24]
Hello,

Thanks for packaging this app, it works like a charm as a Zotero backend !!

Here you left your personnal email !

https://github.com/YunoHost-Apps/my_webdav_ynh/blob/cd1973b1429455c722ca9db4869eabdee7cff10a/scripts/_common.sh#L88

I did a PR [here](https://github.com/YunoHost-Apps/my_webdav_ynh/pull/23) to delete it.

**Comment by Marc-Flender** [comment]
thanks!
